competition:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

import:
    resource: "@ImportBundle/Controller/"
    type:     annotation
    prefix:   /import/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
logout: 
    path: /logout