competition:
    resource: "@CompetitionBundle/Controller/"
    type:     annotation
    prefix:   /

import:
    resource: "@ImportBundle/Controller/"
    type:     annotation
    prefix:   /import/
